// SPDX-License-Identifier: MIT OR Apache-2.0
//! SIP dialog management (RFC 3261 §12).
//!
//! A dialog is a peer-to-peer relationship between two user agents that
//! persists for some time (for the duration of a call, for example). It
//! is identified by the Call-ID together with a local and a remote tag.
//! This module builds and tracks dialogs from the messages that create
//! and confirm them.

use crate::error::{Result, SipError};
use crate::message::Message;
use crate::uri::Uri;

/// Lifecycle state of a dialog.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DialogState {
    /// Created by a non-100 provisional response (`Early`) or the UAS
    /// sending one; not yet confirmed.
    Early,
    /// Confirmed by a 2xx response (UAC) or by sending a 2xx (UAS).
    Confirmed,
}

/// A SIP dialog.
#[derive(Debug, Clone)]
pub struct Dialog {
    /// Call-ID identifying the dialog.
    pub call_id: String,
    /// URI of the local party (the UAC's URI for a UAC-created dialog).
    pub local_uri: Uri,
    /// URI of the remote party.
    pub remote_uri: Uri,
    /// Remote tag (from the peer's `To`/`From` header).
    pub remote_tag: Option<String>,
    /// Local tag (generated by us).
    pub local_tag: String,
    /// Route set, in the order requests should be sent (already reversed
    /// for the UAC per §12.2.1.1).
    pub route_set: Vec<Uri>,
    /// Remote target — the URI from the peer's `Contact` header.
    pub remote_target: Uri,
    /// Whether the dialog is `sips:` (secure).
    pub secure: bool,
    /// Dialog lifecycle state.
    pub state: DialogState,
    /// Next local CSeq number to use for in-dialog requests.
    pub local_cseq: u32,
}

impl Dialog {
    /// Create a dialog as a UAC from a received response. The first
    /// non-100 provisional (Early) or 2xx (Confirmed) response carries
    /// the remote tag that establishes the dialog.
    pub fn from_uac_response(
        response: &Message,
        local_uri: Uri,
        local_tag: &str,
    ) -> Result<Dialog> {
        let code = response.status_line().map(|s| s.code).unwrap_or(0);
        if !(100..=699).contains(&code) {
            return Err(SipError::Transaction("not a response".into()));
        }
        let call_id = response
            .call_id()
            .ok_or_else(|| SipError::Transaction("response missing Call-ID".into()))?
            .to_string();
        let to = response
            .to()
            .ok_or_else(|| SipError::Transaction("response missing To".into()))?;
        let from = response
            .from()
            .ok_or_else(|| SipError::Transaction("response missing From".into()))?;
        let remote_tag = to.tag().map(|t| t.to_string());
        let contact = response
            .contact()
            .first()
            .map(|c| c.uri.clone())
            .ok_or_else(|| SipError::Transaction("response missing Contact".into()))?;
        // UAC route set is the Record-Route set reversed (§12.2.1.1).
        let mut route_set: Vec<Uri> = response
            .headers_for("Record-Route")
            .filter_map(|h| crate::headers::parse_name_addr(&h.value).ok())
            .map(|na| na.uri)
            .collect();
        route_set.reverse();

        let state = if (200..300).contains(&code) {
            DialogState::Confirmed
        } else if code >= 100 && remote_tag.is_some() {
            DialogState::Early
        } else {
            return Err(SipError::Transaction(
                "dialog not established (no To tag yet)".into(),
            ));
        };

        Ok(Dialog {
            call_id,
            local_uri,
            remote_uri: from.uri.clone(),
            remote_tag,
            local_tag: local_tag.to_string(),
            route_set,
            remote_target: contact,
            secure: to.uri.scheme == crate::uri::Scheme::Sips
                || from.uri.scheme == crate::uri::Scheme::Sips,
            state,
            local_cseq: 1,
        })
    }

    /// Create a dialog as a UAS from a received request and the local tag
    /// we assigned to our response's `To` header.
    pub fn from_uas_request(request: &Message, local_tag: &str) -> Result<Dialog> {
        let call_id = request
            .call_id()
            .ok_or_else(|| SipError::Transaction("request missing Call-ID".into()))?
            .to_string();
        let from = request
            .from()
            .ok_or_else(|| SipError::Transaction("request missing From".into()))?;
        let to = request
            .to()
            .ok_or_else(|| SipError::Transaction("request missing To".into()))?;
        let contact = request
            .contact()
            .first()
            .map(|c| c.uri.clone())
            .ok_or_else(|| SipError::Transaction("request missing Contact".into()))?;
        // UAS route set follows the Record-Route order (§12.2.1.2).
        let route_set: Vec<Uri> = request
            .headers_for("Record-Route")
            .filter_map(|h| crate::headers::parse_name_addr(&h.value).ok())
            .map(|na| na.uri)
            .collect();

        Ok(Dialog {
            call_id,
            local_uri: to.uri.clone(),
            remote_uri: from.uri.clone(),
            remote_tag: from.tag().map(|t| t.to_string()),
            local_tag: local_tag.to_string(),
            route_set,
            remote_target: contact,
            secure: from.uri.scheme == crate::uri::Scheme::Sips
                || to.uri.scheme == crate::uri::Scheme::Sips,
            state: DialogState::Early,
            local_cseq: 1,
        })
    }

    /// Confirm an early dialog (once a 2xx is sent/received).
    pub fn confirm(&mut self) {
        self.state = DialogState::Confirmed;
    }

    /// The next local CSeq number, incrementing the counter.
    pub fn next_cseq(&mut self) -> u32 {
        let c = self.local_cseq;
        self.local_cseq += 1;
        c
    }

    /// Whether this dialog is in the confirmed state.
    pub fn is_confirmed(&self) -> bool {
        self.state == DialogState::Confirmed
    }
}
